package pojos;
// Generated 30 nov. 2010 15:49:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name="RESTAURANT"
    ,schema="ROOT"
)
public class Restaurant  implements java.io.Serializable {


     private int restaurantId;
     private Integer fkLocalisationId;
     private String adresse;
     private String nomRestaurant;
     private Integer nbCouverts;
     private Integer rateRestaurant;
     private Double prixMoyen;
     private Double prix;

    public Restaurant() {
    }

	
    public Restaurant(int restaurantId) {
        this.restaurantId = restaurantId;
    }
    public Restaurant(int restaurantId, Integer fkLocalisationId, String adresse, String nomRestaurant, Integer nbCouverts, Integer rateRestaurant, Double prixMoyen, Double prix) {
       this.restaurantId = restaurantId;
       this.fkLocalisationId = fkLocalisationId;
       this.adresse = adresse;
       this.nomRestaurant = nomRestaurant;
       this.nbCouverts = nbCouverts;
       this.rateRestaurant = rateRestaurant;
       this.prixMoyen = prixMoyen;
       this.prix = prix;
    }
   
     @Id 
    
    @Column(name="RESTAURANT_ID", unique=true, nullable=false)
    public int getRestaurantId() {
        return this.restaurantId;
    }
    
    public void setRestaurantId(int restaurantId) {
        this.restaurantId = restaurantId;
    }
    
    @Column(name="FK_LOCALISATION_ID")
    public Integer getFkLocalisationId() {
        return this.fkLocalisationId;
    }
    
    public void setFkLocalisationId(Integer fkLocalisationId) {
        this.fkLocalisationId = fkLocalisationId;
    }
    
    @Column(name="ADRESSE", length=30)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    @Column(name="NOM_RESTAURANT", length=20)
    public String getNomRestaurant() {
        return this.nomRestaurant;
    }
    
    public void setNomRestaurant(String nomRestaurant) {
        this.nomRestaurant = nomRestaurant;
    }
    
    @Column(name="NB_COUVERTS")
    public Integer getNbCouverts() {
        return this.nbCouverts;
    }
    
    public void setNbCouverts(Integer nbCouverts) {
        this.nbCouverts = nbCouverts;
    }
    
    @Column(name="RATE_RESTAURANT")
    public Integer getRateRestaurant() {
        return this.rateRestaurant;
    }
    
    public void setRateRestaurant(Integer rateRestaurant) {
        this.rateRestaurant = rateRestaurant;
    }
    
    @Column(name="PRIX_MOYEN", precision=52, scale=0)
    public Double getPrixMoyen() {
        return this.prixMoyen;
    }
    
    public void setPrixMoyen(Double prixMoyen) {
        this.prixMoyen = prixMoyen;
    }
    
    @Column(name="PRIX", precision=52, scale=0)
    public Double getPrix() {
        return this.prix;
    }
    
    public void setPrix(Double prix) {
        this.prix = prix;
    }




}


