package pojos;
// Generated 30 nov. 2010 15:49:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="CLIENT"
    ,schema="ROOT"
)
public class Client  implements java.io.Serializable {


     private int clientId;
     private String nomClient;
     private String prenomClient;

    public Client() {
    }

	
    public Client(int clientId) {
        this.clientId = clientId;
    }
    public Client(int clientId, String nomClient, String prenomClient) {
       this.clientId = clientId;
       this.nomClient = nomClient;
       this.prenomClient = prenomClient;
    }
   
     @Id 
    
    @Column(name="CLIENT_ID", unique=true, nullable=false)
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    
    @Column(name="NOM_CLIENT", length=12)
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    
    @Column(name="PRENOM_CLIENT", length=12)
    public String getPrenomClient() {
        return this.prenomClient;
    }
    
    public void setPrenomClient(String prenomClient) {
        this.prenomClient = prenomClient;
    }




}


