package pojos;
// Generated 30 nov. 2010 15:49:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReservationHotel generated by hbm2java
 */
@Entity
@Table(name="RESERVATION_HOTEL"
    ,schema="ROOT"
)
public class ReservationHotel  implements java.io.Serializable {


     private int reservationHotelId;
     private Integer fkHotelId;
     private Integer fkIdClient;
     private Date date;

    public ReservationHotel() {
    }

	
    public ReservationHotel(int reservationHotelId) {
        this.reservationHotelId = reservationHotelId;
    }
    public ReservationHotel(int reservationHotelId, Integer fkHotelId, Integer fkIdClient, Date date) {
       this.reservationHotelId = reservationHotelId;
       this.fkHotelId = fkHotelId;
       this.fkIdClient = fkIdClient;
       this.date = date;
    }
   
     @Id 
    
    @Column(name="RESERVATION_HOTEL_ID", unique=true, nullable=false)
    public int getReservationHotelId() {
        return this.reservationHotelId;
    }
    
    public void setReservationHotelId(int reservationHotelId) {
        this.reservationHotelId = reservationHotelId;
    }
    
    @Column(name="FK_HOTEL_ID")
    public Integer getFkHotelId() {
        return this.fkHotelId;
    }
    
    public void setFkHotelId(Integer fkHotelId) {
        this.fkHotelId = fkHotelId;
    }
    
    @Column(name="FK_ID_CLIENT")
    public Integer getFkIdClient() {
        return this.fkIdClient;
    }
    
    public void setFkIdClient(Integer fkIdClient) {
        this.fkIdClient = fkIdClient;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


