/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jReservationHotelPane.java
 *
 * Created on 1 déc. 2010, 10:21:03
 */

package vue;

import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTextField;
import pojos.ReservationHotel;

/**
 *
 * @author Manou
 */
public class jReservationHotelPane extends javax.swing.JPanel implements EntityPane<ReservationHotel>{

    /** Creates new form jReservationHotelPane */
    public jReservationHotelPane() {
        initComponents();
        this.clearField();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        saveButton3 = new javax.swing.JButton();
        fieldFkClient = new javax.swing.JTextField();
        fieldId1 = new javax.swing.JTextField();
        idLabel1 = new javax.swing.JLabel();
        prenomLabel5 = new javax.swing.JLabel();
        buttonFwIDClient = new javax.swing.JButton();
        fieldFkIdHotel = new javax.swing.JTextField();
        buttonFwIDHotel = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        newButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        saveButton3.setText("Save");
        saveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton3ActionPerformed(evt);
            }
        });

        fieldFkClient.setEditable(false);
        fieldFkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkClientActionPerformed(evt);
            }
        });

        fieldId1.setEditable(false);
        fieldId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldId1ActionPerformed(evt);
            }
        });

        idLabel1.setText("Id: ");

        prenomLabel5.setText("Date:");

        buttonFwIDClient.setText("Choix");

        fieldFkIdHotel.setEditable(false);
        fieldFkIdHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdHotelActionPerformed(evt);
            }
        });

        buttonFwIDHotel.setText("Choix");

        newButton1.setText("Clear");

        jLabel1.setText("Client");

        jLabel2.setText("Hotel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(fieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(fieldFkClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(prenomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fieldFkIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonFwIDClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(newButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonFwIDHotel)
                                .addGap(2, 2, 2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFwIDClient)
                        .addGap(7, 7, 7)
                        .addComponent(buttonFwIDHotel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1)
                            .addComponent(fieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldFkClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newButton1)
                                .addComponent(jLabel1)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldFkIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGap(45, 45, 45)
                        .addComponent(saveButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveButton3ActionPerformed

    private void fieldFkClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkClientActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkClientActionPerformed

    private void fieldId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldId1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldId1ActionPerformed

    private void fieldFkIdHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdHotelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkIdHotelActionPerformed

    @Override
    public ReservationHotel getEntity() {
        ReservationHotel result = new ReservationHotel();



        if (fieldFkClient.getText() == "" || fieldFkIdHotel.getText() == "" ) {
            return null;
        } else {
            result.setFkIdClient(Integer.parseInt(fieldFkClient.getText()));
            result.setFkHotelId(Integer.parseInt(fieldFkIdHotel.getText()));

        }


        if (!this.fieldId1.getText().equals("")) {
            result.setReservationHotelId(Integer.parseInt(fieldId1.getText()));
        }

        result.setDate(jDateChooser1.getDate());

        return result;
    }

    @Override
    public void loadEntity(ReservationHotel entity) {
        this.fieldId1.setText(String.valueOf(entity.getReservationHotelId()));
        this.fieldFkClient.setText(String.valueOf(entity.getFkIdClient()));
        this.fieldFkIdHotel.setText(String.valueOf(entity.getFkHotelId()));
        this.jDateChooser1.setDate(entity.getDate());
    }

    @Override
    public void clearField() {
        this.fieldId1.setText("");
        this.fieldFkClient.setText("");
        this.fieldFkIdHotel.setText("");
        this.jDateChooser1.setDate(new Date());
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFwIDClient;
    private javax.swing.JButton buttonFwIDHotel;
    private javax.swing.JTextField fieldFkClient;
    private javax.swing.JTextField fieldFkIdHotel;
    private javax.swing.JTextField fieldId1;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newButton1;
    private javax.swing.JLabel prenomLabel5;
    private javax.swing.JButton saveButton3;
    // End of variables declaration//GEN-END:variables

 


    public JButton getNewButton() {
        return newButton1;
    }

    public JButton getSaveButton() {
        return saveButton3;
    }

    public JTextField getFieldFkClient() {
        return fieldFkClient;
    }

    public JTextField getFieldFkIdHotel() {
        return fieldFkIdHotel;
    }

   public JButton getButtonFwIDClient() {
        return buttonFwIDClient;
    }

    public JButton getButtonFwIDHotel() {
        return buttonFwIDHotel;
    }
}
