/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jReservationPane.java
 *
 * Created on 1 déc. 2010, 10:37:42
 */

package vue;

import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTextField;
import pojos.Voyage;

/**
 *
 * @author Manou
 */
public class jVoyagePane extends javax.swing.JPanel implements EntityPane<Voyage> {

    /** Creates new form jReservationPane */
    public jVoyagePane() {
        initComponents();
        this.jDateChooser1.setDateFormatString("dd/mm/yy");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton3 = new javax.swing.JButton();
        fieldFkClient = new javax.swing.JTextField();
        fieldId1 = new javax.swing.JTextField();
        idLabel1 = new javax.swing.JLabel();
        prenomLabel5 = new javax.swing.JLabel();
        buttonFwIDClient = new javax.swing.JButton();
        fieldFkIdDepart = new javax.swing.JTextField();
        buttonFwIDDepart = new javax.swing.JButton();
        fieldFkIdArrive = new javax.swing.JTextField();
        buttonFwIDArrive = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        newButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        saveButton3.setText("Save");
        saveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton3ActionPerformed(evt);
            }
        });

        fieldFkClient.setEditable(false);
        fieldFkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkClientActionPerformed(evt);
            }
        });

        fieldId1.setEditable(false);
        fieldId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldId1ActionPerformed(evt);
            }
        });

        idLabel1.setText("Id: ");

        prenomLabel5.setText("Date:");

        buttonFwIDClient.setText("Choix");

        fieldFkIdDepart.setEditable(false);
        fieldFkIdDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdDepartActionPerformed(evt);
            }
        });

        buttonFwIDDepart.setText("Choix");

        fieldFkIdArrive.setEditable(false);
        fieldFkIdArrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdArriveActionPerformed(evt);
            }
        });

        buttonFwIDArrive.setText("Choix");

        newButton1.setText("Clear");

        jLabel1.setText("Depart");

        jLabel2.setText("Arrive");

        jLabel3.setText("Client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(fieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prenomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldFkIdArrive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFwIDArrive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldFkIdDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFwIDDepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldFkClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFwIDClient)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(newButton1)
                        .addContainerGap())
                    .addComponent(saveButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1)
                            .addComponent(fieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldFkClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newButton1)
                                .addComponent(buttonFwIDClient)
                                .addComponent(jLabel3)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenomLabel5)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldFkIdDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonFwIDDepart)
                                .addComponent(jLabel1)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldFkIdArrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonFwIDArrive)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(saveButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveButton3ActionPerformed

    private void fieldFkClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkClientActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkClientActionPerformed

    private void fieldId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldId1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldId1ActionPerformed

    private void fieldFkIdDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdDepartActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkIdDepartActionPerformed

    private void fieldFkIdArriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdArriveActionPerformed
        // TODO add your handling code here:
        
}//GEN-LAST:event_fieldFkIdArriveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFwIDArrive;
    private javax.swing.JButton buttonFwIDClient;
    private javax.swing.JButton buttonFwIDDepart;
    private javax.swing.JTextField fieldFkClient;
    private javax.swing.JTextField fieldFkIdArrive;
    private javax.swing.JTextField fieldFkIdDepart;
    private javax.swing.JTextField fieldId1;
    private javax.swing.JLabel idLabel1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newButton1;
    private javax.swing.JLabel prenomLabel5;
    private javax.swing.JButton saveButton3;
    // End of variables declaration//GEN-END:variables

    @Override
    public Voyage getEntity() {
        Voyage result= new Voyage();

        
 
        result.setDate(jDateChooser1.getDate());

        if (!fieldId1.getText().equals("")) {
            result.setVoyageId(Integer.parseInt(fieldId1.getText()));
        }

        if (fieldFkIdArrive.getText()==""|| fieldFkIdDepart.getText()=="" || fieldFkClient.getText()==""){
            return null;
        }else{
            result.setFkClientId(Integer.parseInt(fieldFkClient.getText()));
            result.setFkLocalisationArrive(Integer.parseInt(fieldFkIdArrive.getText()));
            result.setFkLocalisationDepart(Integer.parseInt(fieldFkIdDepart.getText()));

            
        }

           


        return result;
    }

    @Override
    public void loadEntity(Voyage entity) {
       this.fieldId1.setText(String.valueOf(entity.getVoyageId()));
       this.fieldFkClient.setText(String.valueOf(entity.getFkClientId()));
      this.jDateChooser1.setDate(entity.getDate());
       this.fieldFkIdArrive.setText(String.valueOf(entity.getFkLocalisationArrive()));
       this.fieldFkIdDepart.setText(String.valueOf(entity.getFkLocalisationDepart()));

    }

    @Override
    public void clearField() {
    this.jDateChooser1.setDate(new Date());
       this.fieldFkIdArrive.setText("");
       this.fieldFkIdDepart.setText("");
       this.fieldId1.setText("");
       this.fieldFkClient.setText("");
    }


    


    public JButton getNewButton() {
        return newButton1;
    }

    public JButton getSaveButton() {
        return saveButton3;
    }

    public JButton getButtonFwIDArrive() {
        return buttonFwIDArrive;
    }

    public JButton getButtonFwIDClient() {
        return buttonFwIDClient;
    }

    public JButton getButtonFwIDDepart() {
        return buttonFwIDDepart;
    }


    public JTextField getFieldFkClient() {
        return fieldFkClient;
    }

    public JTextField getFieldFkIdArrive() {
        return fieldFkIdArrive;
    }

    public JTextField getFieldFkIdDepart() {
        return fieldFkIdDepart;
    }



}
