/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JpanelClient.java
 *
 * Created on 28 nov. 2010, 13:48:58
 */

package mvca.vue;

/**
 *
 * @author Mister B
 */
public class Jpanelbase extends javax.swing.JPanel {

    /** Creates new form JpanelClient */
    public Jpanelbase() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        saveButton = new javax.swing.JButton();
        nomLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldNom = new javax.swing.JTextField();
        fieldPrenom = new javax.swing.JTextField();
        fieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        saveButton.setBounds(420, 110, 59, 23);
        jLayeredPane1.add(saveButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nomLabel.setText("Nom:");
        nomLabel.setBounds(10, 30, 50, 20);
        jLayeredPane1.add(nomLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Prenom:");
        jLabel2.setBounds(10, 70, 60, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldNom.setText("jTextField1");
        fieldNom.setBounds(60, 30, 100, 20);
        jLayeredPane1.add(fieldNom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldPrenom.setText("jTextField2");
        fieldPrenom.setBounds(60, 70, 100, 20);
        jLayeredPane1.add(fieldPrenom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldId.setEditable(false);
        fieldId.setText("jTextField3");
        fieldId.setBounds(60, 10, 59, 20);
        jLayeredPane1.add(fieldId, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Id: ");
        jLabel1.setBounds(10, 10, 17, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        newButton.setText("New");

        editButton.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldNom;
    private javax.swing.JTextField fieldPrenom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
