/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jRestaurantPane.java
 *
 * Created on 1 déc. 2010, 09:12:10
 */

package mvca.vue;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import mvca.entity.Restaurant;

/**
 *
 * @author Manou
 */
public class jRestaurantPane extends javax.swing.JPanel implements EntityPane<Restaurant> {

    /** Creates new form jRestaurantPane */
    public jRestaurantPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editButton1 = new javax.swing.JButton();
        newButton1 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        saveButton1 = new javax.swing.JButton();
        prenomLabel1 = new javax.swing.JLabel();
        fieldFkLocalisation = new javax.swing.JTextField();
        fieldAdresse = new javax.swing.JTextField();
        fieldId1 = new javax.swing.JTextField();
        idLabel1 = new javax.swing.JLabel();
        nbcouvertLabel = new javax.swing.JLabel();
        fieldNbCouvert = new javax.swing.JTextField();
        prenomLabel4 = new javax.swing.JLabel();
        fieldRestaurant = new javax.swing.JTextField();
        prenomLabel2 = new javax.swing.JLabel();
        fieldPrix = new javax.swing.JTextField();
        nbcouvertLabel1 = new javax.swing.JLabel();
        fieldPrixMoyen = new javax.swing.JTextField();
        prenomLabel5 = new javax.swing.JLabel();
        fieldNote = new javax.swing.JTextField();
        buttonFwIDLocalisation = new javax.swing.JButton();

        editButton1.setText("Edit");

        newButton1.setText("New");

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saveButton1.setText("Save");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        saveButton1.setBounds(470, 110, 70, -1);
        jLayeredPane2.add(saveButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel1.setText("Adresse:");
        prenomLabel1.setBounds(10, 50, 60, -1);
        jLayeredPane2.add(prenomLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldFkLocalisation.setEditable(false);
        fieldFkLocalisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkLocalisationActionPerformed(evt);
            }
        });
        fieldFkLocalisation.setBounds(470, 30, 100, -1);
        jLayeredPane2.add(fieldFkLocalisation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldAdresse.setBounds(90, 50, 100, -1);
        jLayeredPane2.add(fieldAdresse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldId1.setEditable(false);
        fieldId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldId1ActionPerformed(evt);
            }
        });
        fieldId1.setBounds(60, 10, 50, -1);
        jLayeredPane2.add(fieldId1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        idLabel1.setText("Id: ");
        idLabel1.setBounds(10, 10, -1, -1);
        jLayeredPane2.add(idLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nbcouvertLabel.setText("Nb Couvert:");
        nbcouvertLabel.setBounds(10, 70, 70, -1);
        jLayeredPane2.add(nbcouvertLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldNbCouvert.setBounds(90, 70, 100, -1);
        jLayeredPane2.add(fieldNbCouvert, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel4.setText("Nom:");
        prenomLabel4.setBounds(10, 30, 60, -1);
        jLayeredPane2.add(prenomLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldRestaurant.setBounds(90, 30, 100, -1);
        jLayeredPane2.add(fieldRestaurant, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel2.setText("Prix:");
        prenomLabel2.setBounds(200, 50, 60, -1);
        jLayeredPane2.add(prenomLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldPrix.setBounds(260, 50, 100, -1);
        jLayeredPane2.add(fieldPrix, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nbcouvertLabel1.setText("Prix moyen:");
        nbcouvertLabel1.setBounds(200, 70, 60, -1);
        jLayeredPane2.add(nbcouvertLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldPrixMoyen.setBounds(260, 70, 100, -1);
        jLayeredPane2.add(fieldPrixMoyen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel5.setText("Note:");
        prenomLabel5.setBounds(200, 30, 60, -1);
        jLayeredPane2.add(prenomLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldNote.setBounds(260, 30, 100, -1);
        jLayeredPane2.add(fieldNote, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonFwIDLocalisation.setText("Localisation:");
        buttonFwIDLocalisation.setBounds(370, 30, -1, -1);
        jLayeredPane2.add(buttonFwIDLocalisation, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton1)
                    .addComponent(editButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveButton1ActionPerformed

    private void fieldId1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_fieldId1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldId1ActionPerformed

    private void fieldFkLocalisationActionPerformed(ActionEvent evt) {//GEN-FIRST:event_fieldFkLocalisationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFkLocalisationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton buttonFwIDLocalisation;
    javax.swing.JButton editButton1;
    javax.swing.JTextField fieldAdresse;
    javax.swing.JTextField fieldFkLocalisation;
    javax.swing.JTextField fieldId1;
    javax.swing.JTextField fieldNbCouvert;
    javax.swing.JTextField fieldNote;
    javax.swing.JTextField fieldPrix;
    javax.swing.JTextField fieldPrixMoyen;
    javax.swing.JTextField fieldRestaurant;
    javax.swing.JLabel idLabel1;
    javax.swing.JLayeredPane jLayeredPane2;
    javax.swing.JLabel nbcouvertLabel;
    javax.swing.JLabel nbcouvertLabel1;
    javax.swing.JButton newButton1;
    javax.swing.JLabel prenomLabel1;
    javax.swing.JLabel prenomLabel2;
    javax.swing.JLabel prenomLabel4;
    javax.swing.JLabel prenomLabel5;
    javax.swing.JButton saveButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Restaurant getEntity() {
        Restaurant result= new Restaurant();

        if (fieldFkLocalisation.getText()==""){
            return null;
        }else {
            result.setFkLocalisationId(Integer.parseInt(fieldFkLocalisation.getText()));
        }

        if( this.fieldId1.getText()==""){
            result.setRestaurantId(Integer.parseInt(fieldId1.getText()));
        }

        result.setAdresse(fieldAdresse.getText());
        result.setNomRestaurant(fieldRestaurant.getText());



        if( this.fieldNbCouvert.getText()!=""){
            try{
            result.setNbCouverts(Integer.parseInt(fieldNbCouvert.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour nbcouvert", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setNbCouverts(0);
        }

         if( this.fieldNote.getText()!=""){
            try{
            result.setRateRestaurant(Integer.parseInt(fieldNote.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour rank", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setRateRestaurant(0);
        }

         if( this.fieldPrix.getText()!=""){
            try{
            result.setPrix(Double.parseDouble(fieldPrix.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour prix", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setPrix(0d);
        }


       if( this.fieldPrixMoyen.getText()!=""){
            try{
            result.setPrixMoyen(Double.parseDouble(fieldPrixMoyen.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour prix", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setPrixMoyen(0d);
        }

        
      
        
       



        return result;
    }

    @Override
    public void loadEntity(Restaurant entity) {
        this.fieldAdresse.setText(entity.getAdresse());
        this.fieldFkLocalisation.setText(String.valueOf(entity.getFkLocalisationId()));
        this.fieldRestaurant.setText(entity.getNomRestaurant());
        this.fieldNote.setText(String.valueOf(entity.getRateRestaurant()));
        this.fieldId1.setText(String.valueOf(entity.getRestaurantId()));
        this.fieldNbCouvert.setText(String.valueOf(entity.getNbCouverts()));
        this.fieldPrix.setText(String.valueOf(entity.getPrix()));
        this.fieldPrixMoyen.setText(String.valueOf(entity.getPrixMoyen()));
    }

    @Override
    public void clearField() {
        this.fieldAdresse.setText("");
        this.fieldFkLocalisation.setText("");
        this.fieldRestaurant.setText("");
        this.fieldNote.setText("");
        this.fieldId1.setText("");
        this.fieldNbCouvert.setText("");
        this.fieldPrix.setText("");
        this.fieldPrixMoyen.setText("");
        
    }

    public JButton getButtonFwIDLocalisation() {
        return buttonFwIDLocalisation;
    }

    public JButton getEditButton() {
        return editButton1;
    }

    public JButton getNewButton() {
        return newButton1;
    }

    public JTextField getFieldFkLocalisation() {
        return fieldFkLocalisation;
    }

    public JButton getSaveButton() {
        return saveButton1;
    }

   



    

}
