/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jVoyagePane.java
 *
 * Created on 1 déc. 2010, 10:31:38
 */
package mvca.vue;

import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTextField;
import mvca.entity.Reservation;

/**
 *
 * @author Manou
 */
public class jReservationnPane extends javax.swing.JPanel implements EntityPane<Reservation> {

    /** Creates new form jVoyagePane */
    public jReservationnPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton3 = new javax.swing.JButton();
        fieldFkClient = new javax.swing.JTextField();
        fieldId1 = new javax.swing.JTextField();
        idLabel1 = new javax.swing.JLabel();
        prenomLabel5 = new javax.swing.JLabel();
        buttonFwIDClient = new javax.swing.JButton();
        fieldFkIdManif = new javax.swing.JTextField();
        buttonFwIDmanif = new javax.swing.JButton();
        fieldFkIdRestau = new javax.swing.JTextField();
        buttonFwIDrestau = new javax.swing.JButton();
        fieldFkIdHotem = new javax.swing.JTextField();
        buttonFwIDhotel = new javax.swing.JButton();
        fieldFkIdVoyage = new javax.swing.JTextField();
        buttonFwIDvoyage = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        newButton1 = new javax.swing.JButton();
        editButton1 = new javax.swing.JButton();

        saveButton3.setText("Save");
        saveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton3ActionPerformed(evt);
            }
        });

        fieldFkClient.setEditable(false);
        fieldFkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkClientActionPerformed(evt);
            }
        });

        fieldId1.setEditable(false);
        fieldId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldId1ActionPerformed(evt);
            }
        });

        idLabel1.setText("Id: ");

        prenomLabel5.setText("Date:");

        buttonFwIDClient.setText("Client:");

        fieldFkIdManif.setEditable(false);
        fieldFkIdManif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdManifActionPerformed(evt);
            }
        });

        buttonFwIDmanif.setText("Manif:");

        fieldFkIdRestau.setEditable(false);
        fieldFkIdRestau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdRestauActionPerformed(evt);
            }
        });

        buttonFwIDrestau.setText("Restau:");

        fieldFkIdHotem.setEditable(false);
        fieldFkIdHotem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdHotemActionPerformed(evt);
            }
        });

        buttonFwIDhotel.setText("Hotel:");

        fieldFkIdVoyage.setEditable(false);
        fieldFkIdVoyage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkIdVoyageActionPerformed(evt);
            }
        });

        buttonFwIDvoyage.setText("Voyage");

        newButton1.setText("New");

        editButton1.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(fieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(buttonFwIDClient)
                        .addGap(35, 35, 35)
                        .addComponent(fieldFkClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prenomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(buttonFwIDmanif, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldFkIdManif, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(buttonFwIDrestau, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldFkIdRestau, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(buttonFwIDhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldFkIdHotem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(buttonFwIDvoyage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldFkIdVoyage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(newButton1)
                .addGap(15, 15, 15)
                .addComponent(editButton1)
                .addGap(7, 7, 7)
                .addComponent(saveButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1)
                            .addComponent(fieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonFwIDClient)
                            .addComponent(fieldFkClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomLabel5)
                            .addComponent(buttonFwIDmanif)
                            .addComponent(fieldFkIdManif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonFwIDrestau)
                            .addComponent(fieldFkIdRestau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonFwIDhotel)
                            .addComponent(fieldFkIdHotem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonFwIDvoyage)
                            .addComponent(fieldFkIdVoyage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newButton1)
                            .addComponent(editButton1)
                            .addComponent(saveButton3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveButton3ActionPerformed

    private void fieldFkClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkClientActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkClientActionPerformed

    private void fieldId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldId1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldId1ActionPerformed

    private void fieldFkIdManifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdManifActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkIdManifActionPerformed

    private void fieldFkIdRestauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdRestauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFkIdRestauActionPerformed

    private void fieldFkIdHotemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdHotemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFkIdHotemActionPerformed

    private void fieldFkIdVoyageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkIdVoyageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFkIdVoyageActionPerformed

    @Override
    public Reservation getEntity() {
        Reservation result = new Reservation();



        if (fieldFkClient.getText() == "" || fieldFkIdVoyage.getText() == "" || fieldFkIdRestau.getText() == "" || fieldFkIdManif.getText() == "" || fieldFkIdHotem.getText() == "") {
            return null;
        } else {
            result.setFkClientId(Integer.parseInt(fieldFkClient.getText()));
            result.setFkVoyage(Integer.parseInt(fieldFkIdVoyage.getText()));
            result.setFkReserveRestau(Integer.parseInt(fieldFkIdRestau.getText()));
            result.setFkReserveManif(Integer.parseInt(fieldFkIdManif.getText()));
            result.setFkReserveHotel(Integer.parseInt(fieldFkIdHotem.getText()));
        }


        if (this.fieldId1.getText() != "") {
            result.setReservationId(Integer.parseInt(fieldId1.getText()));
        }

        result.setDate(jDateChooser1.getDate());

        return result;
    }

    @Override
    public void loadEntity(Reservation entity) {
        this.fieldId1.setText(String.valueOf(entity.getReservationId()));
        this.fieldFkClient.setText(String.valueOf(entity.getFkClientId()));
        this.fieldFkIdVoyage.setText(String.valueOf(entity.getFkVoyage()));
        this.fieldFkIdRestau.setText(String.valueOf(entity.getFkReserveRestau()));
        this.fieldFkIdManif.setText(String.valueOf(entity.getFkReserveManif()));
        this.fieldFkIdHotem.setText(String.valueOf(entity.getFkReserveHotel()));
        this.jDateChooser1.setDate(entity.getDate());
    }

    @Override
    public void clearField() {
        this.fieldId1.setText("");
        this.fieldFkClient.setText("");
        this.fieldFkIdVoyage.setText("");
        this.fieldFkIdRestau.setText("");
        this.fieldFkIdManif.setText("");
        this.fieldFkIdHotem.setText("");
        this.jDateChooser1.setDate(new Date());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFwIDClient;
    private javax.swing.JButton buttonFwIDhotel;
    private javax.swing.JButton buttonFwIDmanif;
    private javax.swing.JButton buttonFwIDrestau;
    private javax.swing.JButton buttonFwIDvoyage;
    private javax.swing.JButton editButton1;
    private javax.swing.JTextField fieldFkClient;
    private javax.swing.JTextField fieldFkIdHotem;
    private javax.swing.JTextField fieldFkIdManif;
    private javax.swing.JTextField fieldFkIdRestau;
    private javax.swing.JTextField fieldFkIdVoyage;
    private javax.swing.JTextField fieldId1;
    private javax.swing.JLabel idLabel1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton newButton1;
    private javax.swing.JLabel prenomLabel5;
    private javax.swing.JButton saveButton3;
    // End of variables declaration//GEN-END:variables

    public JButton getButtonFwIDClient() {
        return buttonFwIDClient;
    }

    public JButton getButtonFwIDhotel() {
        return buttonFwIDhotel;
    }

    public JButton getButtonFwIDmanif() {
        return buttonFwIDmanif;
    }

    public JButton getButtonFwIDrestau() {
        return buttonFwIDrestau;
    }

    public JButton getButtonFwIDvoyage() {
        return buttonFwIDvoyage;
    }

    public JButton getEditButton() {
        return editButton1;
    }

    public JTextField getFieldFkClient() {
        return fieldFkClient;
    }

    public JTextField getFieldFkIdHotem() {
        return fieldFkIdHotem;
    }

    public JTextField getFieldFkIdManif() {
        return fieldFkIdManif;
    }

    public JTextField getFieldFkIdRestau() {
        return fieldFkIdRestau;
    }

    public JTextField getFieldFkIdVoyage() {
        return fieldFkIdVoyage;
    }

    public JButton getNewButton() {
        return newButton1;
    }

    public JButton getSaveButton() {
        return saveButton3;
    }




}
