/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jTypeManifPane.java
 *
 * Created on 1 déc. 2010, 09:46:58
 */

package mvca.vue;

import javax.swing.JButton;
import mvca.entity.TypeManifestation;

/**
 *
 * @author Manou
 */
public class jTypeManifPane extends javax.swing.JPanel implements EntityPane<TypeManifestation>{

    /** Creates new form jTypeManifPane */
    public jTypeManifPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        nomLabel = new javax.swing.JLabel();
        fieldNom = new javax.swing.JTextField();
        fieldId = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nomLabel.setText("Nom:");

        fieldId.setEditable(false);
        fieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdActionPerformed(evt);
            }
        });

        idLabel.setText("Id: ");

        newButton.setText("New");

        editButton.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addGap(33, 33, 33)
                        .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(newButton)
                        .addGap(5, 5, 5)
                        .addComponent(editButton)
                        .addGap(7, 7, 7)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newButton)
                    .addComponent(editButton)
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveButtonActionPerformed

    private void fieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldNom;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public TypeManifestation getEntity() {
        TypeManifestation result= new TypeManifestation();

          if (!fieldId.getText().equals("")) {
            result.setTypeId(Integer.parseInt(fieldId.getText()));
        }
        result.setNomType(fieldNom.getText());

        return result;
    }

    @Override
    public void loadEntity(TypeManifestation entity) {
       this.fieldId.setText(String.valueOf(entity.getTypeId()));
       this.fieldNom.setText(entity.getNomType());
    }

    @Override
    public void clearField() {
         this.fieldId.setText("");
       this.fieldNom.setText("");
    }

    public JButton getEditButton() {
        return editButton;
    }

    public JButton getNewButton() {
        return newButton;
    }

    public JButton getSaveButton() {
        return saveButton;
    }



    


}
