/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 28 nov. 2010, 13:23:13
 */
package mvca.vue;

import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import java.util.HashMap;
import java.util.LinkedList;

import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;

import mvca.controleur.ControleurGeneric;
import mvca.controleur.ControleurRadio;
import mvca.controleur.ListenerFk;
import mvca.entity.Client;
import mvca.entity.Hotel;
import mvca.entity.Localisation;
import mvca.entity.Manifestation;
import mvca.entity.Reservation;
import mvca.entity.ReservationHotel;
import mvca.entity.ReservationManif;
import mvca.entity.ReservationRestau;
import mvca.entity.Restaurant;
import mvca.entity.TypeManifestation;
import mvca.entity.Voyage;
import mvca.model.Mode;
import mvca.model.ModeParam;
import mvca.modeltable.JTableModelInterface;
import mvca.modeltable.TableModelClient;
import mvca.modeltable.TableModelHotel;
import mvca.modeltable.TableModelLocalisation;
import mvca.modeltable.TableModelManifestation;
import mvca.modeltable.TableModelReservation;
import mvca.modeltable.TableModelReservationHotel;
import mvca.modeltable.TableModelReservationManif;
import mvca.modeltable.TableModelReservationRestau;
import mvca.modeltable.TableModelRestaurant;
import mvca.modeltable.TableModelTypeManif;
import mvca.modeltable.TableModelVoyage;
import mvca.session.HibernateUtil;

/**
 *
 * @author Mister B
 */
public class mainFrame extends javax.swing.JFrame {

    private ControleurRadio radioControleur;
    private LinkedList<ControleurGeneric> listContr;
    private Mode actualmode;
    private HashMap<Mode, ModeParam> modeur;

    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        superJtableBD = new javax.swing.JTable();
        clientRadioButton = new javax.swing.JRadioButton();
        hotelRadioButton = new javax.swing.JRadioButton();
        restaurantRadioButton = new javax.swing.JRadioButton();
        localisationRadioButton = new javax.swing.JRadioButton();
        manifestationRadioButton = new javax.swing.JRadioButton();
        typeManifRadioButton = new javax.swing.JRadioButton();
        voyageRadioButton = new javax.swing.JRadioButton();
        reservationRadioButton = new javax.swing.JRadioButton();
        reservHotelRadioButton = new javax.swing.JRadioButton();
        reservRestauRadioButton = new javax.swing.JRadioButton();
        reservManifRadioButton = new javax.swing.JRadioButton();
        panelAmovible = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back office");

        superJtableBD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        superJtableBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(superJtableBD);

        buttonGroup1.add(clientRadioButton);
        clientRadioButton.setSelected(true);
        clientRadioButton.setText("Client");
        clientRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hotelRadioButton);
        hotelRadioButton.setText("Hotel");
        hotelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(restaurantRadioButton);
        restaurantRadioButton.setText("Restaurant");

        buttonGroup1.add(localisationRadioButton);
        localisationRadioButton.setText("Localisation");

        buttonGroup1.add(manifestationRadioButton);
        manifestationRadioButton.setText("Manifestation");

        buttonGroup1.add(typeManifRadioButton);
        typeManifRadioButton.setText("Type manifestation");

        buttonGroup1.add(voyageRadioButton);
        voyageRadioButton.setText("Voyage");

        buttonGroup1.add(reservationRadioButton);
        reservationRadioButton.setText("Reservation");

        buttonGroup1.add(reservHotelRadioButton);
        reservHotelRadioButton.setText("Reserv Hotel");

        buttonGroup1.add(reservRestauRadioButton);
        reservRestauRadioButton.setText("Reserv Restau");

        buttonGroup1.add(reservManifRadioButton);
        reservManifRadioButton.setText("Reserv Manif");
        reservManifRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservManifRadioButtonActionPerformed(evt);
            }
        });

        panelAmovible.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelAmovibleLayout = new javax.swing.GroupLayout(panelAmovible);
        panelAmovible.setLayout(panelAmovibleLayout);
        panelAmovibleLayout.setHorizontalGroup(
            panelAmovibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelAmovibleLayout.setVerticalGroup(
            panelAmovibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeManifRadioButton)
                    .addComponent(voyageRadioButton)
                    .addComponent(reservationRadioButton)
                    .addComponent(reservHotelRadioButton)
                    .addComponent(manifestationRadioButton)
                    .addComponent(clientRadioButton)
                    .addComponent(hotelRadioButton)
                    .addComponent(restaurantRadioButton)
                    .addComponent(localisationRadioButton)
                    .addComponent(reservRestauRadioButton)
                    .addComponent(reservManifRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAmovible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurantRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localisationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manifestationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeManifRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voyageRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservHotelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservRestauRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservManifRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAmovible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientRadioButtonActionPerformed

    private void hotelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelRadioButtonActionPerformed

    private void reservManifRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservManifRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservManifRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {


        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    /*
                     * {CDE/Motif=com.sun.java.swing.plaf.motif.MotifLookAndFeel,
                    Metal=javax.swing.plaf.metal.MetalLookAndFeel,
                    Nimbus=com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel,
                    Windows=com.sun.java.swing.plaf.windows.WindowsLookAndFeel,
                    Windows Classic=com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel}
                     */


                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
                } catch (Exception e) {
                }
                mainFrame mv = new mainFrame();

                mv.init();
                mv.setVisible(true);





            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clientRadioButton;
    private javax.swing.JRadioButton hotelRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton localisationRadioButton;
    private javax.swing.JRadioButton manifestationRadioButton;
    private javax.swing.JPanel panelAmovible;
    private javax.swing.JRadioButton reservHotelRadioButton;
    private javax.swing.JRadioButton reservManifRadioButton;
    private javax.swing.JRadioButton reservRestauRadioButton;
    private javax.swing.JRadioButton reservationRadioButton;
    private javax.swing.JRadioButton restaurantRadioButton;
    private javax.swing.JTable superJtableBD;
    private javax.swing.JRadioButton typeManifRadioButton;
    private javax.swing.JRadioButton voyageRadioButton;
    // End of variables declaration//GEN-END:variables

    public void placeMachin(JPanel pane) {
        this.panelAmovible.removeAll();
        this.panelAmovible.repaint();
        GridBagLayout fl = new GridBagLayout();

        panelAmovible.setLayout(fl);
        panelAmovible.add(pane);
        /*    GridBagConstraints constraint= new GridBagConstraints();
        constraint.fill= GridBagConstraints.BOTH;
        fl.setConstraints(pane, constraint);
         */

        panelAmovible.revalidate();


    }

    public void setMode(Mode m) {

        ModeParam mp = this.modeur.get(m);
        this.placeMachin(mp.getPanel());
        this.superJtableBD.setModel(mp.getModel());
        superJtableBD.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        this.actualmode = m;


    }

    private void init() {
        listContr = new LinkedList<ControleurGeneric>();
        HibernateUtil<Client> emClient = new HibernateUtil<Client>(Client.class);
        HibernateUtil<Hotel> emHotel = new HibernateUtil<Hotel>(Hotel.class);
        HibernateUtil<Manifestation> emManif = new HibernateUtil<Manifestation>(Manifestation.class);
        HibernateUtil<Localisation> emLoca = new HibernateUtil<Localisation>(Localisation.class);
        HibernateUtil<Reservation> emReserv = new HibernateUtil<Reservation>(Reservation.class);
        HibernateUtil<ReservationHotel> emReservHotel = new HibernateUtil<ReservationHotel>(ReservationHotel.class);
        HibernateUtil<ReservationManif> emReservManif = new HibernateUtil<ReservationManif>(ReservationManif.class);
        HibernateUtil<ReservationRestau> emReservRestau = new HibernateUtil<ReservationRestau>(ReservationRestau.class);
        HibernateUtil<Restaurant> emRestaut = new HibernateUtil<Restaurant>(Restaurant.class);
        HibernateUtil<TypeManifestation> emtypManif = new HibernateUtil<TypeManifestation>(TypeManifestation.class);
        HibernateUtil<Voyage> emVoyage = new HibernateUtil<Voyage>(Voyage.class);

        jClientPane clientPane = new jClientPane();
        jHotelPane hotelPane = new jHotelPane();
        jRestaurantPane restaurantPane = new jRestaurantPane();
        jVoyagePane voyagePane = new jVoyagePane();
        jManifestationPane manifPane = new jManifestationPane();
        jTypeManifPane typeManifPane = new jTypeManifPane();
        jLocalisationPane localisationPane = new jLocalisationPane();
        jReservationHotelPane reservHotelPane = new jReservationHotelPane();
        jReservationRestaurantPane reservRestauPane = new jReservationRestaurantPane();
        jReservationManifPane reservationManifPane = new jReservationManifPane();
        jReservationnPane reservationnPane = new jReservationnPane();


        TableModelClient modelClient = new TableModelClient(emClient);
        TableModelHotel modelHotel = new TableModelHotel(emHotel);
        TableModelLocalisation modelLocalisation = new TableModelLocalisation(emLoca);
        TableModelManifestation modelManifestation = new TableModelManifestation(emManif);
        TableModelReservation modelReservation = new TableModelReservation(emReserv);
        TableModelReservationHotel modelReservationHotel = new TableModelReservationHotel(emReservHotel);
        TableModelReservationManif modelReservationManif = new TableModelReservationManif(emReservManif);
        TableModelReservationRestau modelReservationRestau = new TableModelReservationRestau(emReservRestau);
        TableModelRestaurant modelRestaurant = new TableModelRestaurant(emRestaut);
        TableModelTypeManif modelTypeManif = new TableModelTypeManif(emtypManif);
        TableModelVoyage modelVoyage = new TableModelVoyage(emVoyage);







        ControleurGeneric<Client> controlClient = new ControleurGeneric<Client>();
        ControleurGeneric<Hotel> controlHotel = new ControleurGeneric<Hotel>();
        ControleurGeneric<Restaurant> controlRestaurant = new ControleurGeneric<Restaurant>();
        ControleurGeneric<Localisation> controlLocalisation = new ControleurGeneric<Localisation>();
        ControleurGeneric<Voyage> controlVoyage = new ControleurGeneric<Voyage>();
        ControleurGeneric<TypeManifestation> controlTypeManifestation = new ControleurGeneric<TypeManifestation>();
        ControleurGeneric<Reservation> controlReservation = new ControleurGeneric<Reservation>();
        ControleurGeneric<ReservationHotel> controlReservationHotel = new ControleurGeneric<ReservationHotel>();
        ControleurGeneric<ReservationManif> controlReservationManif = new ControleurGeneric<ReservationManif>();
        ControleurGeneric<ReservationRestau> controlReservationRestau = new ControleurGeneric<ReservationRestau>();
        ControleurGeneric<Manifestation> controlManifestation = new ControleurGeneric<Manifestation>();


        listContr.add(controlClient);
        listContr.add(controlHotel);
        listContr.add(controlRestaurant);
        listContr.add(controlLocalisation);
        listContr.add(controlVoyage);
        listContr.add(controlTypeManifestation);
        listContr.add(controlReservation);
        listContr.add(controlReservationHotel);
        listContr.add(controlReservationManif);
        listContr.add(controlReservationRestau);
        listContr.add(controlManifestation);



        controlClient.setEm(emClient);
        controlClient.setModel(modelClient);
        controlClient.setClientControleur(clientPane);

        controlHotel.setEm(emHotel);
        controlHotel.setModel(modelHotel);
        controlHotel.setClientControleur(hotelPane);

        controlRestaurant.setEm(emRestaut);
        controlRestaurant.setModel(modelRestaurant);
        controlRestaurant.setClientControleur(restaurantPane);

        controlLocalisation.setEm(emLoca);
        controlLocalisation.setModel(modelLocalisation);
        controlLocalisation.setClientControleur(localisationPane);

        controlVoyage.setEm(emVoyage);
        controlVoyage.setModel(modelVoyage);
        controlVoyage.setClientControleur(voyagePane);

        controlTypeManifestation.setEm(emtypManif);
        controlTypeManifestation.setModel(modelTypeManif);
        controlTypeManifestation.setClientControleur(typeManifPane);

        controlReservation.setEm(emReserv);
        controlReservation.setModel(modelReservation);
        controlReservation.setClientControleur(reservationnPane);

        controlReservationHotel.setEm(emReservHotel);
        controlReservationHotel.setModel(modelReservationHotel);
        controlReservationHotel.setClientControleur(reservHotelPane);

        controlReservationManif.setEm(emReservManif);
        controlReservationManif.setModel(modelReservationManif);
        controlReservationManif.setClientControleur(reservationManifPane);

        controlReservationRestau.setEm(emReservRestau);
        controlReservationRestau.setModel(modelReservationRestau);
        controlReservationRestau.setClientControleur(reservRestauPane);

        controlManifestation.setEm(emManif);
        controlManifestation.setModel(modelManifestation);
        controlManifestation.setClientControleur(manifPane);







        clientPane.getNewButton().addActionListener(controlClient.getNewActionListener());
        clientPane.getSaveButton().addActionListener(controlClient.getSaveActionListener());
        clientPane.getEditButton().addActionListener(this.dilateListeuneur());

        hotelPane.getNewButton().addActionListener(controlHotel.getNewActionListener());
        hotelPane.getSaveButton().addActionListener(controlHotel.getSaveActionListener());
        hotelPane.getButtonFwIDLocalisation().addActionListener(new ListenerFk(this, modelLocalisation, hotelPane.getFieldFkLocalisation()));
hotelPane.getEditButton().addActionListener(this.dilateListeuneur());


        restaurantPane.getNewButton().addActionListener(controlRestaurant.getNewActionListener());
        restaurantPane.getSaveButton().addActionListener(controlRestaurant.getSaveActionListener());
        restaurantPane.getButtonFwIDLocalisation().addActionListener(new ListenerFk(this, modelLocalisation, restaurantPane.getFieldFkLocalisation()));
restaurantPane.getEditButton().addActionListener(this.dilateListeuneur());

localisationPane.getNewButton().addActionListener(controlLocalisation.getNewActionListener());
        localisationPane.getSaveButton().addActionListener(controlLocalisation.getSaveActionListener());
localisationPane.getEditButton().addActionListener(this.dilateListeuneur());

        voyagePane.getNewButton().addActionListener(controlVoyage.getNewActionListener());
        voyagePane.getSaveButton().addActionListener(controlVoyage.getSaveActionListener());
        voyagePane.getButtonFwIDArrive().addActionListener(new ListenerFk(this, modelLocalisation, voyagePane.getFieldFkIdArrive()));
        voyagePane.getButtonFwIDClient().addActionListener(new ListenerFk(this, modelClient, voyagePane.getFieldFkClient()));
        voyagePane.getButtonFwIDDepart().addActionListener(new ListenerFk(this, modelLocalisation, voyagePane.getFieldFkIdDepart()));
voyagePane.getEditButton().addActionListener(this.dilateListeuneur());

        typeManifPane.getNewButton().addActionListener(controlTypeManifestation.getNewActionListener());
        typeManifPane.getSaveButton().addActionListener(controlTypeManifestation.getSaveActionListener());
        typeManifPane.getEditButton().addActionListener(this.dilateListeuneur());


        reservationnPane.getNewButton().addActionListener(controlReservation.getNewActionListener());
        reservationnPane.getSaveButton().addActionListener(controlReservation.getSaveActionListener());
        reservationnPane.getButtonFwIDClient().addActionListener(new ListenerFk(this,modelClient, reservationnPane.getFieldFkClient()));
        reservationnPane.getButtonFwIDhotel().addActionListener(new ListenerFk(this,modelHotel, reservationnPane.getFieldFkIdHotem()));
        reservationnPane.getButtonFwIDmanif().addActionListener(new ListenerFk(this,modelManifestation, reservationnPane.getFieldFkIdManif()));
        reservationnPane.getButtonFwIDrestau().addActionListener(new ListenerFk(this,modelRestaurant, reservationnPane.getFieldFkIdRestau()));
        reservationnPane.getButtonFwIDvoyage().addActionListener(new ListenerFk(this,modelVoyage, reservationnPane.getFieldFkIdVoyage()));
reservationnPane.getEditButton().addActionListener(this.dilateListeuneur());
      




        reservHotelPane.getNewButton().addActionListener(controlReservationHotel.getNewActionListener());
        reservHotelPane.getSaveButton().addActionListener(controlReservationHotel.getSaveActionListener());
        reservHotelPane.getButtonFwIDClient().addActionListener(new ListenerFk(this, modelClient, reservHotelPane.getFieldFkClient()));
        reservHotelPane.getButtonFwIDHotel().addActionListener(new ListenerFk(this, modelHotel, reservHotelPane.getFieldFkIdHotel()));
reservHotelPane.getEditButton().addActionListener(this.dilateListeuneur());

        reservationManifPane.getNewButton().addActionListener(controlReservationManif.getNewActionListener());
        reservationManifPane.getSaveButton().addActionListener(controlReservationManif.getSaveActionListener());
        reservationManifPane.getButtonFwIDClient().addActionListener(new ListenerFk(this, modelClient, reservationManifPane.getFieldFkClient()));
        reservationManifPane.getButtonFwIDManif().addActionListener(new ListenerFk(this, modelManifestation, reservationManifPane.getFieldFkIdManif1()));
reservationManifPane.getEditButton().addActionListener(this.dilateListeuneur());


        reservRestauPane.getNewButton().addActionListener(controlReservationRestau.getNewActionListener());
        reservRestauPane.getSaveButton().addActionListener(controlReservationRestau.getSaveActionListener());
        reservRestauPane.getButtonFwIDClient().addActionListener(new ListenerFk(this, modelClient, reservRestauPane.getFieldFkclient()));
        reservRestauPane.getButtonFwIDRestaurant().addActionListener(new ListenerFk(this, modelRestaurant, reservRestauPane.getFieldFkIdRestaurant()));
        reservRestauPane.getEditButton1().addActionListener(this.dilateListeuneur());

        manifPane.getNewButton().addActionListener(controlManifestation.getNewActionListener());
        manifPane.getSaveButton().addActionListener(controlManifestation.getSaveActionListener());
        manifPane.getButtonFwIDLocalisation().addActionListener(new ListenerFk(this, modelLocalisation, manifPane.getFieldFkLocalisation()));
        manifPane.getButtonFwIDType().addActionListener(new ListenerFk(this, modelTypeManif, manifPane.getFieldFkType()));
manifPane.getEditButton().addActionListener(this.dilateListeuneur());









        this.radioControleur = new ControleurRadio(this);
        this.modeur = new HashMap<Mode, ModeParam>();




        modeur.put(Mode.Client, new ModeParam(modelClient, clientPane));
        modeur.put(Mode.Hotel, new ModeParam(modelHotel, hotelPane));
        modeur.put(Mode.Restaurant, new ModeParam(modelRestaurant, restaurantPane));
        modeur.put(Mode.Localisation, new ModeParam(modelLocalisation, localisationPane));
        modeur.put(Mode.TypeManif, new ModeParam(modelTypeManif, typeManifPane));
        modeur.put(Mode.Voyage, new ModeParam(modelVoyage, voyagePane));
        modeur.put(Mode.Manifestation, new ModeParam(modelManifestation, manifPane));
        modeur.put(Mode.Reservation, new ModeParam(modelReservation, reservationnPane));
        modeur.put(Mode.ReservationHotel, new ModeParam(modelReservationHotel, reservHotelPane));
        modeur.put(Mode.ReservationRestaurant, new ModeParam(modelReservationRestau, reservRestauPane));
        modeur.put(Mode.ReservationManif, new ModeParam(modelReservationManif, reservationManifPane));


        this.clientRadioButton.addActionListener(radioControleur.getClientListener());
        this.hotelRadioButton.addActionListener(radioControleur.getHotelListener());
        this.restaurantRadioButton.addActionListener(radioControleur.getRestaurantListener());
        this.reservHotelRadioButton.addActionListener(radioControleur.getReservationHotelListener());
        this.reservManifRadioButton.addActionListener(radioControleur.getReservationManifestationListener());
        this.reservationRadioButton.addActionListener(radioControleur.getReservationListener());
        this.reservRestauRadioButton.addActionListener(radioControleur.getReservationRestaurantListener());
        this.localisationRadioButton.addActionListener(radioControleur.getLocalisationListener());
        this.voyageRadioButton.addActionListener(radioControleur.getVoyageListener());
        this.typeManifRadioButton.addActionListener(radioControleur.getTypeManifestationListener());
        this.manifestationRadioButton.addActionListener(radioControleur.getManifestationListener());


        this.superJtableBD.addMouseListener(this.mouseListener());


        this.setMode(Mode.Client);
    }

    public HashMap<Mode, ModeParam> getModeur() {
        return modeur;
    }

    private MouseListener mouseListener() {


        return new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {


                ModeParam ff = modeur.get(actualmode);
                EntityPane pane = (EntityPane) ff.getPanel();
                JTableModelInterface model = ff.getModel();

                pane.loadEntity(model.getRows(superJtableBD.getSelectedRow()));

            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        };
    }



    private ActionListener dilateListeuneur(){
        return new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                 ModeParam ff = modeur.get(actualmode);
                EntityPane pane = (EntityPane) ff.getPanel();
                JTableModelInterface model = ff.getModel();
                
                Integer dd= model.getIDForSelected(superJtableBD.getSelectedRow());
                if (dd!=null){
                model.getEm().delete(dd);
                model.refresh();
                pane.clearField();
                }
               

            }
        };
    }

}
