/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 28 nov. 2010, 13:23:13
 */

package mvca.vue;

import mvca.modeltable.TableModelClient;

/**
 *
 * @author Mister B
 */
public class mainFrame extends javax.swing.JFrame {

    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        superJtableBD = new javax.swing.JTable();
        clientRadioButton = new javax.swing.JRadioButton();
        hotelRadioButton = new javax.swing.JRadioButton();
        restaurantRadioButton = new javax.swing.JRadioButton();
        localisationRadioButton = new javax.swing.JRadioButton();
        manifestationRadioButton = new javax.swing.JRadioButton();
        typeManifRadioButton = new javax.swing.JRadioButton();
        voyageRadioButton = new javax.swing.JRadioButton();
        reservationRadioButton = new javax.swing.JRadioButton();
        reservHotelRadioButton = new javax.swing.JRadioButton();
        reservRestauRadioButton = new javax.swing.JRadioButton();
        reservManifRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back office");

        superJtableBD.setModel(new TableModelClient() );
        jScrollPane1.setViewportView(superJtableBD);

        buttonGroup1.add(clientRadioButton);
        clientRadioButton.setText("Client");
        clientRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hotelRadioButton);
        hotelRadioButton.setText("Hotel");
        hotelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(restaurantRadioButton);
        restaurantRadioButton.setText("Restaurant");

        buttonGroup1.add(localisationRadioButton);
        localisationRadioButton.setText("Localisation");

        buttonGroup1.add(manifestationRadioButton);
        manifestationRadioButton.setText("Manifestation");

        buttonGroup1.add(typeManifRadioButton);
        typeManifRadioButton.setText("Type manifestation");

        buttonGroup1.add(voyageRadioButton);
        voyageRadioButton.setText("Voyage");

        buttonGroup1.add(reservationRadioButton);
        reservationRadioButton.setText("Reservation");

        buttonGroup1.add(reservHotelRadioButton);
        reservHotelRadioButton.setText("Reserv Hotel");

        buttonGroup1.add(reservRestauRadioButton);
        reservRestauRadioButton.setText("Reserv Restau");

        buttonGroup1.add(reservManifRadioButton);
        reservManifRadioButton.setText("Reserv Manif");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeManifRadioButton)
                    .addComponent(voyageRadioButton)
                    .addComponent(reservationRadioButton)
                    .addComponent(reservHotelRadioButton)
                    .addComponent(reservRestauRadioButton)
                    .addComponent(reservManifRadioButton)
                    .addComponent(manifestationRadioButton)
                    .addComponent(clientRadioButton)
                    .addComponent(hotelRadioButton)
                    .addComponent(restaurantRadioButton)
                    .addComponent(localisationRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurantRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localisationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manifestationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeManifRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voyageRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservHotelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservRestauRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservManifRadioButton)
                        .addGap(58, 58, 58))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientRadioButtonActionPerformed

    private void hotelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelRadioButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clientRadioButton;
    private javax.swing.JRadioButton hotelRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton localisationRadioButton;
    private javax.swing.JRadioButton manifestationRadioButton;
    private javax.swing.JRadioButton reservHotelRadioButton;
    private javax.swing.JRadioButton reservManifRadioButton;
    private javax.swing.JRadioButton reservRestauRadioButton;
    private javax.swing.JRadioButton reservationRadioButton;
    private javax.swing.JRadioButton restaurantRadioButton;
    private javax.swing.JTable superJtableBD;
    private javax.swing.JRadioButton typeManifRadioButton;
    private javax.swing.JRadioButton voyageRadioButton;
    // End of variables declaration//GEN-END:variables

}
