package mvca.entity;
// Generated 30 nov. 2010 15:49:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Localisation generated by hbm2java
 */
@Entity
@Table(name="LOCALISATION"
    ,schema="ROOT"
)
public class Localisation  implements java.io.Serializable {


     private int localisationId;
     private String pays;
     private String ville;

    public Localisation() {
    }

	
    public Localisation(int localisationId) {
        this.localisationId = localisationId;
    }
    public Localisation(int localisationId, String pays, String ville) {
       this.localisationId = localisationId;
       this.pays = pays;
       this.ville = ville;
    }
   
     @Id 
    
    @Column(name="LOCALISATION_ID", unique=true, nullable=false)
    public int getLocalisationId() {
        return this.localisationId;
    }
    
    public void setLocalisationId(int localisationId) {
        this.localisationId = localisationId;
    }
    
    @Column(name="PAYS", length=15)
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }
    
    @Column(name="VILLE", length=15)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }




}


