/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jHotelPane.java
 *
 * Created on 1 déc. 2010, 09:32:50
 */

package mvca.vue;

import javax.swing.JOptionPane;
import mvca.entity.Hotel;

/**
 *
 * @author Manou
 */
public class jHotelPane extends javax.swing.JPanel implements EntityPane<Hotel>{

    /** Creates new form jHotelPane */
    public jHotelPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newButton1 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        saveButton1 = new javax.swing.JButton();
        prenomLabel1 = new javax.swing.JLabel();
        fieldFkLocalisation = new javax.swing.JTextField();
        fieldAdresse = new javax.swing.JTextField();
        fieldId1 = new javax.swing.JTextField();
        idLabel1 = new javax.swing.JLabel();
        nbcouvertLabel = new javax.swing.JLabel();
        fieldNbCouvert = new javax.swing.JTextField();
        prenomLabel4 = new javax.swing.JLabel();
        fieldHotel = new javax.swing.JTextField();
        prenomLabel2 = new javax.swing.JLabel();
        fieldPrix = new javax.swing.JTextField();
        nbcouvertLabel1 = new javax.swing.JLabel();
        fieldPrixMoyen = new javax.swing.JTextField();
        prenomLabel5 = new javax.swing.JLabel();
        fieldNote = new javax.swing.JTextField();
        buttonFwIDLocalisation = new javax.swing.JButton();
        editButton1 = new javax.swing.JButton();

        newButton1.setText("New");

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saveButton1.setText("Save");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        saveButton1.setBounds(450, 110, 70, -1);
        jLayeredPane2.add(saveButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel1.setText("Adresse:");
        prenomLabel1.setBounds(10, 50, 60, -1);
        jLayeredPane2.add(prenomLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldFkLocalisation.setEditable(false);
        fieldFkLocalisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFkLocalisationActionPerformed(evt);
            }
        });
        fieldFkLocalisation.setBounds(170, 100, 100, -1);
        jLayeredPane2.add(fieldFkLocalisation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldAdresse.setBounds(70, 50, 100, -1);
        jLayeredPane2.add(fieldAdresse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fieldId1.setEditable(false);
        fieldId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldId1ActionPerformed(evt);
            }
        });
        fieldId1.setBounds(60, 10, 50, -1);
        jLayeredPane2.add(fieldId1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        idLabel1.setText("Id: ");
        idLabel1.setBounds(10, 10, -1, -1);
        jLayeredPane2.add(idLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nbcouvertLabel.setText("Nb couvert:");
        nbcouvertLabel.setBounds(10, 70, 60, -1);
        jLayeredPane2.add(nbcouvertLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldNbCouvert.setBounds(70, 70, 100, -1);
        jLayeredPane2.add(fieldNbCouvert, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel4.setText("Nom:");
        prenomLabel4.setBounds(10, 30, 60, -1);
        jLayeredPane2.add(prenomLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldHotel.setBounds(70, 30, 100, -1);
        jLayeredPane2.add(fieldHotel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel2.setText("Prix:");
        prenomLabel2.setBounds(180, 50, 60, -1);
        jLayeredPane2.add(prenomLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldPrix.setBounds(240, 50, 100, -1);
        jLayeredPane2.add(fieldPrix, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nbcouvertLabel1.setText("Prix moyen:");
        nbcouvertLabel1.setBounds(180, 70, 60, -1);
        jLayeredPane2.add(nbcouvertLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldPrixMoyen.setBounds(240, 70, 100, -1);
        jLayeredPane2.add(fieldPrixMoyen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prenomLabel5.setText("Note:");
        prenomLabel5.setBounds(180, 30, 60, -1);
        jLayeredPane2.add(prenomLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldNote.setBounds(240, 30, 100, -1);
        jLayeredPane2.add(fieldNote, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonFwIDLocalisation.setText("Localisation:");
        buttonFwIDLocalisation.setBounds(70, 100, -1, -1);
        jLayeredPane2.add(buttonFwIDLocalisation, javax.swing.JLayeredPane.DEFAULT_LAYER);

        editButton1.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton1)
                    .addComponent(editButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveButton1ActionPerformed

    private void fieldFkLocalisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFkLocalisationActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldFkLocalisationActionPerformed

    private void fieldId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldId1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldId1ActionPerformed





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFwIDLocalisation;
    private javax.swing.JButton editButton1;
    private javax.swing.JTextField fieldAdresse;
    private javax.swing.JTextField fieldFkLocalisation;
    private javax.swing.JTextField fieldHotel;
    private javax.swing.JTextField fieldId1;
    private javax.swing.JTextField fieldNbCouvert;
    private javax.swing.JTextField fieldNote;
    private javax.swing.JTextField fieldPrix;
    private javax.swing.JTextField fieldPrixMoyen;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel nbcouvertLabel;
    private javax.swing.JLabel nbcouvertLabel1;
    private javax.swing.JButton newButton1;
    private javax.swing.JLabel prenomLabel1;
    private javax.swing.JLabel prenomLabel2;
    private javax.swing.JLabel prenomLabel4;
    private javax.swing.JLabel prenomLabel5;
    private javax.swing.JButton saveButton1;
    // End of variables declaration//GEN-END:variables


      @Override
    public Hotel getEntity() {
        Hotel result= new Hotel();

        if (fieldFkLocalisation.getText()==""){
            return null;
        }else {
            result.setFkLocalisationId(Integer.parseInt(fieldFkLocalisation.getText()));
        }

        if( this.fieldId1.getText()==""){
            result.setHotelId(Integer.parseInt(fieldId1.getText()));
        }

        result.setAdresse(fieldAdresse.getText());
        result.setNomHotel(fieldHotel.getText());



        if( this.fieldNbCouvert.getText()!=""){
            try{
            result.setNbChambre(Integer.parseInt(fieldNbCouvert.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour nbcouvert", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setNbChambre(0);
        }

         if( this.fieldNote.getText()!=""){
            try{
            result.setRankHotel(Integer.parseInt(fieldNote.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour rank", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setRankHotel(0);
        }

         if( this.fieldPrix.getText()!=""){
            try{
            result.setPrix(Double.parseDouble(fieldPrix.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour prix", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setPrix(0d);
        }


       if( this.fieldPrixMoyen.getText()!=""){
            try{
            result.setPrixMoyen(Double.parseDouble(fieldPrixMoyen.getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(getParent(), "Entier requis pour prix", "Dialog",
        JOptionPane.ERROR_MESSAGE);
                 return null;
            }
        }else{
        result.setPrixMoyen(0d);
        }








        return result;
    }

    @Override
    public void loadEntity(Hotel entity) {
        this.fieldAdresse.setText(entity.getAdresse());
        this.fieldFkLocalisation.setText(String.valueOf(entity.getFkLocalisationId()));
        this.fieldHotel.setText(entity.getNomHotel());
        this.fieldNote.setText(String.valueOf(entity.getRankHotel()));
        this.fieldId1.setText(String.valueOf(entity.getHotelId()));
        this.fieldNbCouvert.setText(String.valueOf(entity.getNbChambre()));
        this.fieldPrix.setText(String.valueOf(entity.getPrix()));
        this.fieldPrixMoyen.setText(String.valueOf(entity.getPrixMoyen()));
    }

    @Override
    public void clearField() {
        this.fieldAdresse.setText("");
        this.fieldFkLocalisation.setText("");
        this.fieldHotel.setText("");
        this.fieldNote.setText("");
        this.fieldId1.setText("");
        this.fieldNbCouvert.setText("");
        this.fieldPrix.setText("");
        this.fieldPrixMoyen.setText("");

    }

}
