/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 28 nov. 2010, 13:23:13
 */

package mvca.vue;

import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import mvca.controleur.controleurClient;
import mvca.entity.Client;
import mvca.modeltable.TableModelClient;
import mvca.session.HibernateUtil;
import org.hibernate.Hibernate;

/**
 *
 * @author Mister B
 */
public class mainFrame extends javax.swing.JFrame {

    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        superJtableBD = new javax.swing.JTable();
        clientRadioButton = new javax.swing.JRadioButton();
        hotelRadioButton = new javax.swing.JRadioButton();
        restaurantRadioButton = new javax.swing.JRadioButton();
        localisationRadioButton = new javax.swing.JRadioButton();
        manifestationRadioButton = new javax.swing.JRadioButton();
        typeManifRadioButton = new javax.swing.JRadioButton();
        voyageRadioButton = new javax.swing.JRadioButton();
        reservationRadioButton = new javax.swing.JRadioButton();
        reservHotelRadioButton = new javax.swing.JRadioButton();
        reservRestauRadioButton = new javax.swing.JRadioButton();
        reservManifRadioButton = new javax.swing.JRadioButton();
        panelAmovible = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back office");

        superJtableBD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        superJtableBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(superJtableBD);

        buttonGroup1.add(clientRadioButton);
        clientRadioButton.setSelected(true);
        clientRadioButton.setText("Client");
        clientRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hotelRadioButton);
        hotelRadioButton.setText("Hotel");
        hotelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(restaurantRadioButton);
        restaurantRadioButton.setText("Restaurant");

        buttonGroup1.add(localisationRadioButton);
        localisationRadioButton.setText("Localisation");

        buttonGroup1.add(manifestationRadioButton);
        manifestationRadioButton.setText("Manifestation");

        buttonGroup1.add(typeManifRadioButton);
        typeManifRadioButton.setText("Type manifestation");

        buttonGroup1.add(voyageRadioButton);
        voyageRadioButton.setText("Voyage");

        buttonGroup1.add(reservationRadioButton);
        reservationRadioButton.setText("Reservation");

        buttonGroup1.add(reservHotelRadioButton);
        reservHotelRadioButton.setText("Reserv Hotel");

        buttonGroup1.add(reservRestauRadioButton);
        reservRestauRadioButton.setText("Reserv Restau");

        buttonGroup1.add(reservManifRadioButton);
        reservManifRadioButton.setText("Reserv Manif");

        panelAmovible.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelAmovibleLayout = new javax.swing.GroupLayout(panelAmovible);
        panelAmovible.setLayout(panelAmovibleLayout);
        panelAmovibleLayout.setHorizontalGroup(
            panelAmovibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        panelAmovibleLayout.setVerticalGroup(
            panelAmovibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeManifRadioButton)
                    .addComponent(voyageRadioButton)
                    .addComponent(reservationRadioButton)
                    .addComponent(reservHotelRadioButton)
                    .addComponent(reservRestauRadioButton)
                    .addComponent(reservManifRadioButton)
                    .addComponent(manifestationRadioButton)
                    .addComponent(clientRadioButton)
                    .addComponent(hotelRadioButton)
                    .addComponent(restaurantRadioButton)
                    .addComponent(localisationRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAmovible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurantRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localisationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manifestationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeManifRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voyageRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservHotelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservRestauRadioButton))
                    .addComponent(panelAmovible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservManifRadioButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientRadioButtonActionPerformed

    private void hotelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelRadioButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame mv=  new mainFrame();

            mv.listenerEttout();

                mv.setVisible(true);
                


               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clientRadioButton;
    private javax.swing.JRadioButton hotelRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton localisationRadioButton;
    private javax.swing.JRadioButton manifestationRadioButton;
    private javax.swing.JPanel panelAmovible;
    private javax.swing.JRadioButton reservHotelRadioButton;
    private javax.swing.JRadioButton reservManifRadioButton;
    private javax.swing.JRadioButton reservRestauRadioButton;
    private javax.swing.JRadioButton reservationRadioButton;
    private javax.swing.JRadioButton restaurantRadioButton;
    private javax.swing.JTable superJtableBD;
    private javax.swing.JRadioButton typeManifRadioButton;
    private javax.swing.JRadioButton voyageRadioButton;
    // End of variables declaration//GEN-END:variables

 
public void placeMachin(JPanel pane){
    this.panelAmovible.removeAll();

    GridBagLayout fl= new GridBagLayout();
   
    panelAmovible.setLayout(fl);
       panelAmovible.add(pane);
       GridBagConstraints constraint= new GridBagConstraints();
       constraint.fill= GridBagConstraints.BOTH;
        fl.setConstraints(pane, constraint);
    panelAmovible.repaint();
 

}


public void listenerEttout(){

    jClientPane jj=new jClientPane();
    HibernateUtil<Client> em= new HibernateUtil<Client>(Client.class);
    TableModelClient gg= new TableModelClient(em);

    controleurClient control= new controleurClient();
    
    

    control.setEm(em);
    control.setModel(gg);
    control.setTable(this.superJtableBD);
    control.setClientControleur(jj);


    superJtableBD.setModel(gg);
    superJtableBD.addMouseListener(control.getTableModelListener());

    /*
     *
     *   public JButton getEditButton() {
        return editButton;
    }

    public JButton getNewButton() {
        return newButton;
    }

    public JButton getSaveButton() {
        return saveButton;
     *
     */

    
    jj.getNewButton().addActionListener(control.getNewActionListener());
    jj.getSaveButton().addActionListener(control.getSaveActionListener());

this.placeMachin(jj);
    
}

}
