package mvca.entity;
// Generated 30 nov. 2010 15:49:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Manifestation generated by hbm2java
 */
@Entity
@Table(name="MANIFESTATION"
    ,schema="ROOT"
)
public class Manifestation  implements java.io.Serializable {


     private int manifestationId;
     private Integer fkLocalisationId;
     private Integer fkIdType;
     private Integer nbPlace;
     private String nomManifestation;
     private Date date;
     private String adresse;
     private String description;
     private Double prix;

    public Manifestation() {
    }

	
    public Manifestation(int manifestationId) {
        this.manifestationId = manifestationId;
    }
    public Manifestation(int manifestationId, Integer fkLocalisationId, Integer fkIdType, Integer nbPlace, String nomManifestation, Date date, String adresse, String description, Double prix) {
       this.manifestationId = manifestationId;
       this.fkLocalisationId = fkLocalisationId;
       this.fkIdType = fkIdType;
       this.nbPlace = nbPlace;
       this.nomManifestation = nomManifestation;
       this.date = date;
       this.adresse = adresse;
       this.description = description;
       this.prix = prix;
    }
   
     @Id 
    
    @Column(name="MANIFESTATION_ID", unique=true, nullable=false)
    public int getManifestationId() {
        return this.manifestationId;
    }
    
    public void setManifestationId(int manifestationId) {
        this.manifestationId = manifestationId;
    }
    
    @Column(name="FK_LOCALISATION_ID")
    public Integer getFkLocalisationId() {
        return this.fkLocalisationId;
    }
    
    public void setFkLocalisationId(Integer fkLocalisationId) {
        this.fkLocalisationId = fkLocalisationId;
    }
    
    @Column(name="FK_ID_TYPE")
    public Integer getFkIdType() {
        return this.fkIdType;
    }
    
    public void setFkIdType(Integer fkIdType) {
        this.fkIdType = fkIdType;
    }
    
    @Column(name="NB_PLACE")
    public Integer getNbPlace() {
        return this.nbPlace;
    }
    
    public void setNbPlace(Integer nbPlace) {
        this.nbPlace = nbPlace;
    }
    
    @Column(name="NOM_MANIFESTATION", length=20)
    public String getNomManifestation() {
        return this.nomManifestation;
    }
    
    public void setNomManifestation(String nomManifestation) {
        this.nomManifestation = nomManifestation;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="ADRESSE", length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    @Column(name="DESCRIPTION", length=80)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="PRIX", precision=52, scale=0)
    public Double getPrix() {
        return this.prix;
    }
    
    public void setPrix(Double prix) {
        this.prix = prix;
    }




}


