<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ScubaDivingWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ScubaDivingWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ScubaDivingWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://j2ee.netbeans.org/wsdl/DivingBooking/ScubaDiving">
    <import location="ScubaDiving.wsdl" namespace="http://j2ee.netbeans.org/wsdl/DivingBooking/ScubaDiving"/>
    <plnk:partnerLinkType name="ScubaDiving">
        <plnk:role name="ScubaDiving" portType="ns:ScubaDivingPortType"/>
    </plnk:partnerLinkType>
</definitions>

